// Conversation state constants
const STATES = {
  // Entry states
  WELCOME: 'WELCOME',
  SERVICE_SELECTION: 'SERVICE_SELECTION',

  // SEO Audit flow
  SEO_COLLECT_URL: 'SEO_COLLECT_URL',
  SEO_ANALYZING: 'SEO_ANALYZING',
  SEO_RESULTS: 'SEO_RESULTS',
  SEO_FOLLOW_UP: 'SEO_FOLLOW_UP',

  // Web Development flow
  WEB_COLLECT_NAME: 'WEB_COLLECT_NAME',
  WEB_COLLECT_INDUSTRY: 'WEB_COLLECT_INDUSTRY',
  WEB_COLLECT_SERVICES: 'WEB_COLLECT_SERVICES',
  WEB_COLLECT_COLORS: 'WEB_COLLECT_COLORS',
  WEB_COLLECT_LOGO: 'WEB_COLLECT_LOGO',
  WEB_COLLECT_CONTACT: 'WEB_COLLECT_CONTACT',
  WEB_GENERATING: 'WEB_GENERATING',
  WEB_GENERATION_FAILED: 'WEB_GENERATION_FAILED',
  WEB_PREVIEW: 'WEB_PREVIEW',
  WEB_REVISIONS: 'WEB_REVISIONS',

  // App Development flow
  APP_COLLECT_REQUIREMENTS: 'APP_COLLECT_REQUIREMENTS',
  APP_PROPOSAL: 'APP_PROPOSAL',
  APP_FOLLOW_UP: 'APP_FOLLOW_UP',

  // Marketing flow
  MARKETING_COLLECT_DETAILS: 'MARKETING_COLLECT_DETAILS',
  MARKETING_STRATEGY: 'MARKETING_STRATEGY',
  MARKETING_FOLLOW_UP: 'MARKETING_FOLLOW_UP',

  // General
  GENERAL_CHAT: 'GENERAL_CHAT',

  // Informative / FAQ bot
  INFORMATIVE_CHAT: 'INFORMATIVE_CHAT',

  // Sales bot (Bytes Platform v2)
  SALES_CHAT: 'SALES_CHAT',

  // Meeting scheduling flow
  SCHEDULE_COLLECT_DATE: 'SCHEDULE_COLLECT_DATE',
  SCHEDULE_COLLECT_TIME: 'SCHEDULE_COLLECT_TIME',
  SCHEDULE_CONFIRM: 'SCHEDULE_CONFIRM',

  // AI Chatbot SaaS flow
  CB_COLLECT_NAME: 'CB_COLLECT_NAME',
  CB_COLLECT_INDUSTRY: 'CB_COLLECT_INDUSTRY',
  CB_COLLECT_FAQS: 'CB_COLLECT_FAQS',
  CB_COLLECT_SERVICES: 'CB_COLLECT_SERVICES',
  CB_COLLECT_HOURS: 'CB_COLLECT_HOURS',
  CB_COLLECT_LOCATION: 'CB_COLLECT_LOCATION',
  CB_GENERATING: 'CB_GENERATING',
  CB_DEMO_SENT: 'CB_DEMO_SENT',
  CB_FOLLOW_UP: 'CB_FOLLOW_UP',
};

// Service button IDs used in interactive messages
const SERVICE_IDS = {
  SEO_AUDIT: 'svc_seo',
  WEB_DEV: 'svc_webdev',
  APP_DEV: 'svc_appdev',
  MARKETING: 'svc_marketing',
  GENERAL: 'svc_general',
  INFORMATIVE: 'svc_info',
  CHATBOT: 'svc_chatbot',
};

module.exports = { STATES, SERVICE_IDS };
