'use client';

import { Loader2 } from 'lucide-react';
import type { ContentStatus } from '@/lib/pixie-lab/contentAgentTypes';

/** Shared visual kit for the Content Agent surfaces. Uses the Pixie Lab
 *  design tokens (--pl-*) and the content-agent gold accent. */
export const ACCENT = '#D4AF37';

export const inputClass =
  'w-full rounded-lg border border-[var(--pl-border)] bg-[var(--pl-surface-soft)] px-3 py-2 text-[13px] text-[var(--pl-text)] outline-none focus:border-[var(--pl-green)] transition disabled:opacity-50';

export function PrimaryButton({
  children,
  busy,
  ...rest
}: React.ButtonHTMLAttributes<HTMLButtonElement> & { busy?: boolean }) {
  return (
    <button
      {...rest}
      className="inline-flex items-center gap-2 rounded-xl px-5 py-2.5 text-[13.5px] font-bold text-[#02120f] transition disabled:opacity-50"
      style={{ background: ACCENT }}
    >
      {busy ? <Loader2 size={15} className="animate-spin" /> : null}
      {children}
    </button>
  );
}

export function GhostButton({ children, ...rest }: React.ButtonHTMLAttributes<HTMLButtonElement>) {
  return (
    <button
      {...rest}
      className="inline-flex items-center gap-2 rounded-xl border border-[var(--pl-border)] px-4 py-2.5 text-[13px] font-semibold text-[var(--pl-text-soft)] transition hover:text-[var(--pl-text)] disabled:opacity-50"
    >
      {children}
    </button>
  );
}

/** Mock vs real provider indicator — never claims a real provider when mock. */
export function ModeBadge({ mock }: { mock: boolean }) {
  return (
    <span
      className="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10.5px] font-bold uppercase tracking-wide"
      style={
        mock
          ? { borderColor: 'var(--pl-border)', color: 'var(--pl-text-muted)' }
          : { borderColor: ACCENT, color: ACCENT }
      }
      title={mock ? 'Generated in local mock mode — no paid API calls.' : 'Generated by a live model provider.'}
    >
      {mock ? 'Mock' : 'Live'}
    </span>
  );
}

const STATUS_STYLE: Record<ContentStatus, { label: string; dot: string }> = {
  draft: { label: 'Draft', dot: '#9aa0a6' },
  ready: { label: 'Ready', dot: '#3fb950' },
  archived: { label: 'Archived', dot: '#d29922' },
};

export function StatusBadge({ status }: { status: ContentStatus }) {
  const s = STATUS_STYLE[status] || STATUS_STYLE.draft;
  return (
    <span className="inline-flex items-center gap-1.5 rounded-full border border-[var(--pl-border)] px-2 py-0.5 text-[11px] font-semibold text-[var(--pl-text-soft)]">
      <span className="h-1.5 w-1.5 rounded-full" style={{ background: s.dot }} aria-hidden />
      {s.label}
    </span>
  );
}

export function Spinner({ label = 'Loading…' }: { label?: string }) {
  return (
    <div className="flex items-center gap-2 py-8 text-[13px] text-[var(--pl-text-muted)]" role="status" aria-live="polite">
      <Loader2 size={16} className="animate-spin" />
      {label}
    </div>
  );
}

export function ErrorNote({ children }: { children: React.ReactNode }) {
  return (
    <p role="alert" className="rounded-lg border border-amber-500/30 bg-amber-500/5 px-3 py-2 text-[12.5px] text-amber-500">
      {children}
    </p>
  );
}

export function EmptyState({ title, body, action }: { title: string; body: string; action?: React.ReactNode }) {
  return (
    <div className="rounded-2xl border border-dashed border-[var(--pl-border)] bg-[var(--pl-surface)] p-8 text-center">
      <p className="font-display text-[1.05rem] font-extrabold tracking-tight text-[var(--pl-text)]">{title}</p>
      <p className="mx-auto mt-1.5 max-w-md text-[13.5px] text-[var(--pl-text-muted)]">{body}</p>
      {action && <div className="mt-5 flex justify-center">{action}</div>}
    </div>
  );
}

/** Copy text to clipboard; returns a promise so callers can toast on resolve. */
export async function copyText(text: string): Promise<boolean> {
  try {
    if (navigator?.clipboard?.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }
  } catch {
    /* fall through */
  }
  return false;
}
