// AUTO-GENERATED by scripts/generateDemoSites.js — do not edit by hand.
// Run `node scripts/generateDemoSites.js` to regenerate the sites and
// update this file with fresh Netlify preview URLs.

export interface DemoSite {
  id: string;
  label: string;
  businessName: string;
  industry: string;
  city: string;
  prompt: string;
  url: string;
}

export const DEMO_SITES: DemoSite[] = [
  {
    "id": "hvac",
    "label": "HVAC",
    "prompt": "I need a website for my HVAC company in Austin. We do AC repair, heating, duct cleaning, and emergency service.",
    "businessName": "Austin Climate Pros",
    "industry": "HVAC",
    "city": "Austin, TX",
    "url": "https://preview-1776447034475.netlify.app"
  },
  {
    "id": "real-estate",
    "label": "Real Estate",
    "prompt": "I'm a realtor in Austin. I work with luxury buyers and first-time homeowners across Westlake, Circle C, and Barton Hills.",
    "businessName": "Sarah Mitchell",
    "industry": "Real Estate",
    "city": "Austin, TX",
    "url": "https://preview-1776447076417.netlify.app"
  },
  {
    "id": "salon",
    "label": "Salon",
    "prompt": "I run a hair salon in Miami Beach. I need a website with online booking, an Instagram feed, and pricing for cuts and color.",
    "businessName": "Luna Beauty Studio",
    "industry": "Hair Salon",
    "city": "Miami Beach, FL",
    "url": "https://preview-1776447111358.netlify.app"
  },
  {
    "id": "generic",
    "label": "Coffee Shop",
    "prompt": "I own a specialty coffee shop in Portland. I want a clean site with our drinks, wholesale beans, and contact info.",
    "businessName": "Byte Coffee Co.",
    "industry": "Specialty coffee shop",
    "city": "Portland, OR",
    "url": "https://preview-1776447150399.netlify.app"
  }
];
